### ISSUE TITLE
C++ files not listed in projects

### ISSUE THREAD

**Issue by Gaztin** [polymonster/premake-android-studio#5]
My C++ files for all of my projects seem to build correctly, but Android Studio is failing to add them to the project view, hence all auto completion and highlighting is broken.
![](https://media.discordapp.net/attachments/415973908467023884/601896188966338564/unknown.png)

My source files are located under `src/` and my project files are generated under `build/android-studio/` and if I move my source files there as well, AS adds them without problem. It seems to treat my source files as "external". Is there something I can do to fix this?

**Comment by polymonster** [comment]
I am currently using android studio 3.1.4 and C++ files are being correctly added to the project and are visible, but I think a co-worked with newer version of android studio is seeing this same issue.

I will take a look into it.

**Comment by polymonster** [comment]
Turns out it is just header files we cant see in android studio solution explorer. Our projects are laid out like this:

project
- build
-- android
- source
-- cpp files
- template
-- android
--- defauly_activity.java
- premake5.lua

We only have 1 java file which is our main activity and this is located in a different folder to the cpp files... are you mixing java and cpp files under the same directory? I did have some issues with mixed cpp and java files when initially making this project.

**Comment by Gaztin** [comment]
I see. My project structure looks something like this:
```
+-- build
|   +-- android-studio/
|       +-- <generated-project-files>
+-- src
    +-- android/
    |   +-- java/<package-name>/
    |   |   +-- <Java files>
    |   +-- res/values/
    |   |   +-- strings.xml
    |   +-- AndroidManifest.xml
    +-- main.cpp
```
So I'm not directly 'mixing' java and cpp files, but they do share parent directories beneath the project root (`src` in this case).

**Comment by Gaztin** [comment]
Revisiting this two years later I can see that the error seems to have gone away. Was most likely a bug related to gradle or Android Studio. Closing this!

**Comment by polymonster** [comment]
Great to hear! Thanks for updating.
